# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Style checking

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          # CLI arguments
          args: --color always --check lua/
